#!/usr/bin/env python
"""Smoke tests for YazKlinik SQL dialect helpers."""
from __future__ import annotations

import json
import re

import yazklinik_sql_dialect as d


def _normalize_sql(sql_text: str) -> str:
    text = str(sql_text or "")
    # Identifier quoting differences ("key" vs key) are semantically equal here.
    text = re.sub(r'"([a-zA-Z_][a-zA-Z0-9_]*)"', r"\1", text)
    text = re.sub(r"\s+", " ", text).strip().lower()
    return text


def run_checks():
    checks = []
    converted = d.qmark_to_psycopg(
        "SELECT * FROM patients WHERE a=? AND note='why?' AND b=? -- ?")
    checks.append({
        "name": "qmark_to_psycopg_quotes",
        "ok": converted == "SELECT * FROM patients WHERE a=%s AND note='why?' AND b=%s -- ?",
        "converted": converted,
    })
    ignore = d.translate_sql(
        "INSERT OR IGNORE INTO patient_demographics(patient_key, updated_at) VALUES(?, ?)",
        ("p1", "now"),
        dialect="postgresql",
    )
    checks.append({
        "name": "insert_or_ignore",
        "ok": ignore.sql == (
            "INSERT INTO patient_demographics(patient_key, updated_at) VALUES(%s, %s) "
            "ON CONFLICT DO NOTHING"),
        "sql": ignore.sql,
    })
    replace = d.translate_sql(
        "INSERT OR REPLACE INTO settings(key, value) VALUES(?, ?)",
        ("a", "b"),
        dialect="postgresql",
    )
    replace_norm = _normalize_sql(replace.sql)
    checks.append({
        "name": "insert_or_replace_settings",
        "ok": (
            "insert into settings(key, value) values(%s, %s)" in replace_norm
            and "on conflict (key) do update set value=excluded.value" in replace_norm
        ),
        "sql": replace.sql,
    })
    replace_multi = d.translate_sql(
        "INSERT OR REPLACE INTO voice_profiles("
        "owner_type, owner_key, display_name, updated_at) VALUES(?,?,?,?)",
        ("doctor", "doktor", "Dr", "now"),
        dialect="postgresql",
    )
    replace_multi_norm = _normalize_sql(replace_multi.sql)
    checks.append({
        "name": "insert_or_replace_voice_profiles",
        "ok": (
            "on conflict (owner_type, owner_key)" in replace_multi_norm
            and "display_name=excluded.display_name" in replace_multi_norm
            and "updated_at=excluded.updated_at" in replace_multi_norm
        ),
        "sql": replace_multi.sql,
    })
    pragma = d.translate_sql("PRAGMA busy_timeout=30000", dialect="postgresql")
    checks.append({
        "name": "pragma_skip",
        "ok": pragma.sql is None and pragma.action == "skip",
        "action": pragma.action,
    })
    autoinc = d.translate_sql(
        "CREATE TABLE demo (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT)",
        dialect="postgresql",
    )
    checks.append({
        "name": "autoincrement_to_identity",
        "ok": "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in str(autoinc.sql),
        "sql": autoinc.sql,
    })
    table = d.table_exists_sql("patients", dialect="postgresql")
    checks.append({
        "name": "table_exists_pg",
        "ok": "to_regclass" in str(table.sql) and table.params == ("patients",),
        "sql": table.sql,
    })
    sqlite_master_qmark = d.translate_sql(
        "SELECT 1 FROM sqlite_master WHERE type='table' AND name=?",
        ("patients",),
        dialect="postgresql",
    )
    checks.append({
        "name": "sqlite_master_qmark_to_pg",
        "ok": "to_regclass" in str(sqlite_master_qmark.sql)
              and sqlite_master_qmark.params == ("patients",),
        "sql": sqlite_master_qmark.sql,
    })
    sqlite_master_literal = d.translate_sql(
        "SELECT name FROM sqlite_master WHERE type='table' AND name='patients'",
        dialect="postgresql",
    )
    checks.append({
        "name": "sqlite_master_literal_to_pg",
        "ok": "AS name WHERE to_regclass" in str(sqlite_master_literal.sql)
              and sqlite_master_literal.params == ("patients", "patients"),
        "sql": sqlite_master_literal.sql,
    })
    pragma_table_info = d.translate_sql(
        "PRAGMA table_info(patients)",
        dialect="postgresql",
    )
    checks.append({
        "name": "pragma_table_info_to_pg",
        "ok": "information_schema.columns" in str(pragma_table_info.sql)
              and pragma_table_info.params == ("patients", "patients"),
        "sql": pragma_table_info.sql,
    })
    pragma_sqlite = d.translate_sql("PRAGMA busy_timeout=30000", dialect="sqlite")
    checks.append({
        "name": "sqlite_passthrough",
        "ok": pragma_sqlite.sql == "PRAGMA busy_timeout=30000"
              and pragma_sqlite.action == "execute",
        "sql": pragma_sqlite.sql,
    })
    return {
        "ok": all(c.get("ok") for c in checks),
        "dialect_version": d.DIALECT_VERSION,
        "checks": checks,
    }


def main() -> int:
    report = run_checks()
    print("YAZKLINIK_SQL_DIALECT_CHECK_" + ("OK" if report.get("ok") else "FAIL"))
    print(json.dumps(report, ensure_ascii=False, indent=2))
    return 0 if report.get("ok") else 1


if __name__ == "__main__":
    raise SystemExit(main())
