#!/usr/bin/env python
"""Scan YazKlinik SQL usage for PostgreSQL compatibility risks.

This is a static risk scanner, not a code transformer. It lets us move from
"sqlite3.connect references are gone" to "which SQL patterns still need work
before PostgreSQL primary can be enabled".
"""
from __future__ import annotations

import argparse
import ast
import json
import re
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, Iterable, List


ROOT = Path(__file__).resolve().parent
REPORT_DIR = ROOT / "runtime_state" / "postgres_sql_compat"
LAST_REPORT = REPORT_DIR / "last_report.json"
LAST_PRIORITY_REPORT = REPORT_DIR / "priority_report.md"
SCANNER_VERSION = "2026.05.19-pg-sql-compat-scan"
AST_PARSE_MAX_BYTES = 10 * 1024 * 1024

DEFAULT_FILES = [
    "yazklinik_web.py",
    "yazklinik_v68.py",
    "yazklinik_feature_sync.py",
    "yazklinik_common.py",
    "yazklinik_config.py",
]

PATTERNS = [
    {
        "key": "sqlite_pragma",
        "severity": "high",
        "regex": r"\bPRAGMA\b",
        "note": "SQLite PRAGMA has no direct PostgreSQL equivalent.",
    },
    {
        "key": "sqlite_rowid",
        "severity": "high",
        "regex": r"\browid\b",
        "note": "SQLite rowid must become explicit primary key/identity logic.",
    },
    {
        "key": "sqlite_lastrowid",
        "severity": "high",
        "regex": r"\blastrowid\b",
        "note": "Use PostgreSQL RETURNING id instead of cursor.lastrowid.",
    },
    {
        "key": "sqlite_sequence",
        "severity": "high",
        "regex": r"\bsqlite_sequence\b",
        "note": "Use PostgreSQL sequences/identity reset instead.",
    },
    {
        "key": "sqlite_master",
        "severity": "high",
        "regex": r"\bsqlite_master\b",
        "note": "Use information_schema/pg_catalog in PostgreSQL.",
    },
    {
        "key": "insert_or_replace",
        "severity": "high",
        "regex": r"\bINSERT\s+OR\s+REPLACE\b",
        "note": "Use INSERT ... ON CONFLICT DO UPDATE.",
    },
    {
        "key": "insert_or_ignore",
        "severity": "high",
        "regex": r"\bINSERT\s+OR\s+IGNORE\b",
        "note": "Use INSERT ... ON CONFLICT DO NOTHING.",
    },
    {
        "key": "sqlite_autoincrement",
        "severity": "high",
        "regex": r"\bAUTOINCREMENT\b",
        "note": "Use GENERATED BY DEFAULT AS IDENTITY/BIGSERIAL.",
    },
    {
        "key": "qmark_placeholders",
        "severity": "medium",
        "regex": r"\?",
        "note": "SQLite qmark params may need psycopg parameter style review.",
    },
    {
        "key": "sqlite_datetime_now",
        "severity": "medium",
        "regex": r"\b(?:datetime|date|time)\s*\(\s*['\"]now['\"]",
        "note": "Use now()/current_date/current_time in PostgreSQL.",
    },
    {
        "key": "sqlite_strftime",
        "severity": "medium",
        "regex": r"\bstrftime\s*\(",
        "note": "Use to_char/date_trunc/extract in PostgreSQL.",
    },
    {
        "key": "sqlite_julianday",
        "severity": "medium",
        "regex": r"\bjulianday\s*\(",
        "note": "Use PostgreSQL date arithmetic/extract epoch.",
    },
    {
        "key": "sqlite_ifnull",
        "severity": "medium",
        "regex": r"\bIFNULL\s*\(",
        "note": "Use COALESCE.",
    },
]

SQL_TOKEN_RE = re.compile(
    r"\b("
    r"SELECT|INSERT|UPDATE|DELETE|CREATE|ALTER|DROP|PRAGMA|VACUUM|REINDEX|"
    r"ANALYZE|WITH|BEGIN|COMMIT|ROLLBACK|REPLACE|ON\s+CONFLICT|FROM|WHERE|"
    r"TABLE|INDEX"
    r")\b",
    flags=re.IGNORECASE,
)
CODE_PATTERNS = {
    "sqlite_lastrowid": re.compile(r"\blastrowid\b", flags=re.IGNORECASE),
}
RISK_BUCKETS = (
    "runtime_blocker",
    "maintenance_sqlite_only",
    "schema_migration",
    "adapter_covered",
    "adapter_candidate",
    "low_noise",
)


def _iter_files(files: Iterable[str]) -> Iterable[Path]:
    for item in files:
        path = ROOT / item
        if path.exists() and path.is_file():
            yield path


def _line_for_offset(line_starts: List[int], offset: int) -> int:
    line_no = 1
    for idx, start in enumerate(line_starts):
        if start > offset:
            break
        line_no = idx + 1
    return line_no


def _sql_candidates(path: Path, text: str) -> List[Dict[str, Any]]:
    """Return SQL-like string/code fragments only, avoiding whole-file noise."""
    candidates: List[Dict[str, Any]] = []
    tree = None
    ast_skipped = False
    try:
        ast_skipped = path.stat().st_size > AST_PARSE_MAX_BYTES
    except Exception:
        ast_skipped = len(text) > AST_PARSE_MAX_BYTES
    if not ast_skipped:
        try:
            tree = ast.parse(text, filename=str(path))
        except SyntaxError:
            tree = None
    else:
        tree = None

    if tree is not None:
        for node in ast.walk(tree):
            if isinstance(node, ast.Constant) and isinstance(node.value, str):
                value = node.value
                if SQL_TOKEN_RE.search(value):
                    candidates.append({
                        "kind": "sql_string",
                        "line": int(getattr(node, "lineno", 1) or 1),
                        "text": value,
                    })
            elif isinstance(node, ast.JoinedStr):
                parts = []
                for value in node.values:
                    if isinstance(value, ast.Constant) and isinstance(value.value, str):
                        parts.append(value.value)
                    else:
                        parts.append("{}")
                joined = "".join(parts)
                if SQL_TOKEN_RE.search(joined):
                    candidates.append({
                        "kind": "sql_fstring",
                        "line": int(getattr(node, "lineno", 1) or 1),
                        "text": joined,
                    })

    for line_no, line in enumerate(text.splitlines(), start=1):
        if tree is None and SQL_TOKEN_RE.search(line):
            candidates.append({
                "kind": "sql_line",
                "line": line_no,
                "text": line,
            })
        for key, regex in CODE_PATTERNS.items():
            if regex.search(line):
                candidates.append({
                    "kind": "code_line",
                    "line": line_no,
                    "text": line,
                    "forced_keys": [key],
                })
    return candidates


def _risk_bucket(pattern_key: str, file_name: str, line_no: int,
                 sample_text: str) -> str:
    text = str(sample_text or "").strip().lower()
    if text.startswith("#"):
        return "low_noise"
    if file_name == "yazklinik_v68.py" and 1400 <= int(line_no or 0) <= 1700:
        return "maintenance_sqlite_only"
    if pattern_key == "qmark_placeholders":
        return "adapter_covered"
    if pattern_key == "insert_or_ignore":
        return "adapter_covered"
    if pattern_key == "sqlite_lastrowid":
        return "adapter_covered"
    if pattern_key == "insert_or_replace":
        return "adapter_covered"
    if pattern_key == "sqlite_master":
        if "select name from sqlite_master" in text:
            return "adapter_covered"
        if "type='table'" in text or 'type="table"' in text:
            return "adapter_covered"
        return "runtime_blocker"
    if pattern_key == "sqlite_autoincrement":
        return "adapter_covered"
    if pattern_key == "sqlite_sequence":
        return "maintenance_sqlite_only"
    if pattern_key == "sqlite_pragma":
        if text == "pragma":
            return "low_noise"
        if "headers[" in text and "pragma" in text:
            return "low_noise"
        if "headers.pop(" in text and "pragma" in text:
            return "low_noise"
        if "table_info" in text:
            return "adapter_covered"
        if any(token in text for token in (
            "journal_mode", "synchronous", "busy_timeout", "wal_checkpoint",
            "optimize", "foreign_keys", "cache_size", "temp_store", "mmap_size",
            "page_size", "wal_autocheckpoint", "quick_check", "integrity_check",
            "foreign_key_check", "page_count", "freelist_count",
        )):
            return "adapter_covered"
        return "runtime_blocker"
    if pattern_key in {"sqlite_rowid", "sqlite_lastrowid",
                       "insert_or_replace", "insert_or_ignore",
                       "sqlite_datetime_now", "sqlite_strftime",
                       "sqlite_julianday", "sqlite_ifnull"}:
        if 108600 <= int(line_no or 0) <= 109000:
            return "maintenance_sqlite_only"
        if 165700 <= int(line_no or 0) <= 168100:
            return "maintenance_sqlite_only"
        return "runtime_blocker"
    return "low_noise"


def scan_sql_compat(files: Iterable[str] | None = None,
                    max_examples: int = 40) -> Dict[str, Any]:
    chosen = list(files or DEFAULT_FILES)
    report: Dict[str, Any] = {
        "ok": True,
        "scanner_version": SCANNER_VERSION,
        "started_at": datetime.now().isoformat(timespec="seconds"),
        "files": [],
        "summary": {
            "files_scanned": 0,
            "high": 0,
            "medium": 0,
            "low": 0,
            "total": 0,
        },
        "risk_summary": {key: 0 for key in RISK_BUCKETS},
        "patterns": {p["key"]: {"severity": p["severity"], "count": 0}
                     for p in PATTERNS},
        "examples": [],
        "priority_examples": [],
        "sql_compat_ready": False,
    }

    for path in _iter_files(chosen):
        text = path.read_text(encoding="utf-8", errors="replace")
        file_item = {"file": path.name, "matches": {}}
        report["summary"]["files_scanned"] += 1
        candidates = _sql_candidates(path, text)
        for pattern in PATTERNS:
            regex = re.compile(pattern["regex"], flags=re.IGNORECASE)
            matches = []
            for candidate in candidates:
                forced_keys = set(candidate.get("forced_keys") or [])
                if forced_keys and pattern["key"] not in forced_keys:
                    continue
                if forced_keys:
                    found = list(regex.finditer(candidate["text"]))
                elif pattern["key"] in CODE_PATTERNS:
                    continue
                else:
                    found = list(regex.finditer(candidate["text"]))
                for match in found:
                    matches.append((candidate, match))
            count = len(matches)
            file_item["matches"][pattern["key"]] = count
            report["patterns"][pattern["key"]]["count"] += count
            severity = pattern["severity"]
            report["summary"][severity] += count
            report["summary"]["total"] += count
            if count and len(report["examples"]) < max_examples:
                for candidate, match in matches[:3]:
                    if len(report["examples"]) >= max_examples:
                        break
                    line_no = int(candidate.get("line") or 1)
                    sample_text = str(candidate.get("text") or "")
                    sample_line = sample_text.splitlines()[0] if sample_text else ""
                    report["examples"].append({
                        "file": path.name,
                        "line": line_no,
                        "key": pattern["key"],
                        "severity": severity,
                        "note": pattern["note"],
                        "source_kind": candidate.get("kind"),
                        "text": sample_line.strip()[:220],
                    })
            for candidate, match in matches:
                line_no = int(candidate.get("line") or 1)
                sample_text = str(candidate.get("text") or "")
                bucket = _risk_bucket(pattern["key"], path.name, line_no, sample_text)
                report["risk_summary"][bucket] += 1
                if bucket == "runtime_blocker" and len(report["priority_examples"]) < max_examples:
                    sample_line = sample_text.splitlines()[0] if sample_text else ""
                    report["priority_examples"].append({
                        "file": path.name,
                        "line": line_no,
                        "key": pattern["key"],
                        "severity": severity,
                        "bucket": bucket,
                        "note": pattern["note"],
                        "source_kind": candidate.get("kind"),
                        "text": sample_line.strip()[:220],
                    })
        report["files"].append(file_item)

    report["sql_compat_ready"] = (
        int(report["risk_summary"]["runtime_blocker"] or 0) == 0
        and int(report["risk_summary"].get("schema_migration", 0) or 0) == 0
        and int(report["risk_summary"].get("adapter_candidate", 0) or 0) == 0
    )
    report["finished_at"] = datetime.now().isoformat(timespec="seconds")

    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    LAST_REPORT.write_text(
        json.dumps(report, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    _write_priority_report(report)
    return report


def _write_priority_report(report: Dict[str, Any]) -> None:
    summary = report.get("summary") or {}
    risk_summary = report.get("risk_summary") or {}
    lines = [
        "# PostgreSQL SQL Compatibility Priority Report",
        "",
        f"Generated: {report.get('finished_at') or ''}",
        f"Scanner: {report.get('scanner_version') or ''}",
        "",
        "## Summary",
        "",
        f"- Files scanned: {summary.get('files_scanned', 0)}",
        f"- Total matches: {summary.get('total', 0)}",
        f"- High pattern matches: {summary.get('high', 0)}",
        f"- Medium pattern matches: {summary.get('medium', 0)}",
        f"- Runtime blockers: {risk_summary.get('runtime_blocker', 0)}",
        f"- Adapter-covered items: {risk_summary.get('adapter_covered', 0)}",
        f"- Maintenance-only SQLite items: {risk_summary.get('maintenance_sqlite_only', 0)}",
        f"- Schema migration items: {risk_summary.get('schema_migration', 0)}",
        f"- Adapter candidate items: {risk_summary.get('adapter_candidate', 0)}",
        "",
        "## First fix order",
        "",
        "1. Runtime blockers: rowid, lastrowid, sqlite_master, INSERT OR REPLACE/IGNORE in live routes.",
        "2. Schema migration: remaining CREATE TABLE strings must be covered by the SQL dialect adapter or PG migration DDL.",
        "3. Adapter candidates: qmark placeholders should be handled by the SQL dialect adapter, not manually one by one.",
        "4. Maintenance-only SQLite items stay blocked behind sqlite maintenance guard until PG equivalents exist.",
        "",
        "## Top runtime blocker examples",
        "",
    ]
    examples = report.get("priority_examples") or []
    if not examples:
        lines.append("- None")
    for item in examples[:30]:
        lines.append(
            f"- {item.get('file')}:{item.get('line')} "
            f"[{item.get('key')}] {item.get('text')}"
        )
    lines.append("")
    LAST_PRIORITY_REPORT.write_text("\n".join(lines), encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Scan PostgreSQL SQL compatibility risks")
    parser.add_argument("--json", action="store_true", help="Print full JSON")
    parser.add_argument("--max-examples", type=int, default=40)
    parser.add_argument("--files", nargs="*", default=None)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    report = scan_sql_compat(files=args.files, max_examples=args.max_examples)
    if args.json:
        print(json.dumps(report, ensure_ascii=False, indent=2))
    else:
        summary = report.get("summary") or {}
        print("POSTGRES_SQL_COMPAT_SCAN_OK")
        print(
            f"files={summary.get('files_scanned')} total={summary.get('total')} "
            f"high={summary.get('high')} medium={summary.get('medium')} "
            f"runtime_blockers={report.get('risk_summary', {}).get('runtime_blocker')} "
            f"sql_compat_ready={report.get('sql_compat_ready')}"
        )
        print(f"report={LAST_REPORT}")
        print(f"priority_report={LAST_PRIORITY_REPORT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
