#!/usr/bin/env python
"""PostgreSQL primary runtime simulation without changing live config."""
from __future__ import annotations

import json
import os
from datetime import datetime
from typing import Any, Dict

import yazklinik_db_adapter as adapter


SIM_VERSION = "2026.05.19-pg-runtime-sim"


def runtime_simulation() -> Dict[str, Any]:
    report: Dict[str, Any] = {
        "ok": False,
        "sim_version": SIM_VERSION,
        "started_at": datetime.now().isoformat(timespec="seconds"),
        "checks": [],
        "blockers": [],
    }

    try:
        with adapter.postgres_connection() as con:
            with con.cursor() as cur:
                cur.execute("SELECT 1")
                one = cur.fetchone()[0]
        report["checks"].append({"name": "postgres_connect", "ok": one == 1})
    except Exception as exc:
        report["checks"].append({"name": "postgres_connect", "ok": False, "error": str(exc)})
        report["blockers"].append(f"PostgreSQL connect failed: {exc}")

    try:
        with adapter.postgres_dialect_connection() as con:
            cur = con.execute("SELECT ?::int AS value", (42,))
            row = cur.fetchone()
            value = row[0] if row else None
            table_cur = con.execute(
                "SELECT 1 FROM sqlite_master WHERE type='table' AND name=?",
                ("patients",),
            )
            table_exists = bool(table_cur.fetchone())
            info_cur = con.execute("PRAGMA table_info(patients)")
            table_info = info_cur.fetchall()
            table_info_cols = [str(row[1]) for row in table_info if len(row) > 1]
            con.execute(
                "CREATE TEMP TABLE yk_pg_runtime_sim_ids("
                "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                "name TEXT)"
            )
            insert_cur = con.execute(
                "INSERT INTO yk_pg_runtime_sim_ids(name) VALUES(?)",
                ("probe",),
            )
            lastrowid = insert_cur.lastrowid
            con.execute(
                "CREATE TEMP TABLE yk_pg_runtime_sim_autoinc("
                "id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT)"
            )
            auto_cur = con.execute(
                "INSERT INTO yk_pg_runtime_sim_autoinc(name) VALUES(?)",
                ("auto",),
            )
            auto_id = auto_cur.lastrowid
            con.execute(
                "CREATE TEMP TABLE voice_profiles("
                "owner_type TEXT, owner_key TEXT, display_name TEXT, updated_at TEXT, "
                "UNIQUE(owner_type, owner_key))"
            )
            con.execute(
                "INSERT OR REPLACE INTO voice_profiles("
                "owner_type, owner_key, display_name, updated_at) VALUES(?,?,?,?)",
                ("doctor", "doktor", "Ilk", "t1"),
            )
            con.execute(
                "INSERT OR REPLACE INTO voice_profiles("
                "owner_type, owner_key, display_name, updated_at) VALUES(?,?,?,?)",
                ("doctor", "doktor", "Guncel", "t2"),
            )
            replace_row = con.execute(
                "SELECT display_name, updated_at FROM voice_profiles "
                "WHERE owner_type=? AND owner_key=?",
                ("doctor", "doktor"),
            ).fetchone()
            skipped = con.execute("PRAGMA busy_timeout=30000")
            skipped_rows = skipped.fetchall()
        report["checks"].append({
            "name": "postgres_dialect_execute",
            "ok": (
                value == 42
                and table_exists
                and "folder_key" in table_info_cols
                and lastrowid == 1
                and auto_id == 1
                and replace_row
                and replace_row[0] == "Guncel"
                and skipped_rows == []
            ),
            "value": value,
            "table_exists": table_exists,
            "table_info_cols_sample": table_info_cols[:8],
            "lastrowid": lastrowid,
            "autoincrement_identity_id": auto_id,
            "insert_or_replace": list(replace_row) if replace_row else None,
            "skipped_rows": skipped_rows,
        })
    except Exception as exc:
        report["checks"].append({
            "name": "postgres_dialect_execute",
            "ok": False,
            "error": str(exc),
        })
        report["blockers"].append(f"PostgreSQL dialect execute failed: {exc}")

    old_primary = os.environ.get("YAZKLINIK_DB_PRIMARY")
    old_mode = os.environ.get("YAZKLINIK_POSTGRES_MODE")
    runtime_ready = str(os.environ.get("YAZKLINIK_POSTGRES_RUNTIME_ADAPTER_READY") or "").strip() == "1"
    sql_ready = str(os.environ.get("YAZKLINIK_POSTGRES_SQL_COMPAT_READY") or "").strip() == "1"
    try:
        os.environ["YAZKLINIK_DB_PRIMARY"] = "postgresql"
        os.environ["YAZKLINIK_POSTGRES_MODE"] = "primary"
        try:
            with adapter.runtime_connection("forced-postgres-primary-sim") as con:
                count_row = con.execute("SELECT COUNT(*) FROM patients").fetchone()
                report["checks"].append({
                    "name": "forced_primary_runtime",
                    "ok": bool(runtime_ready and sql_ready and count_row and int(count_row[0]) >= 0),
                    "opened": type(con).__name__,
                    "patient_count": int(count_row[0]) if count_row else None,
                })
                if not (runtime_ready and sql_ready):
                    report["blockers"].append("Primary guard allowed PostgreSQL primary before ready flags")
        except RuntimeError as exc:
            report["checks"].append({
                "name": "forced_primary_guard",
                "ok": not (runtime_ready and sql_ready),
                "blocked": str(exc),
            })
            if runtime_ready and sql_ready:
                report["blockers"].append(f"PostgreSQL primary still blocked after ready flags: {exc}")
    finally:
        if old_primary is None:
            os.environ.pop("YAZKLINIK_DB_PRIMARY", None)
        else:
            os.environ["YAZKLINIK_DB_PRIMARY"] = old_primary
        if old_mode is None:
            os.environ.pop("YAZKLINIK_POSTGRES_MODE", None)
        else:
            os.environ["YAZKLINIK_POSTGRES_MODE"] = old_mode

    try:
        import YAZKLINIK_POSTGRES_SQL_COMPAT_SCAN as scan
        compat = scan.scan_sql_compat(max_examples=10)
        summary = compat.get("summary") or {}
        risk_summary = compat.get("risk_summary") or {}
        report["checks"].append({
            "name": "sql_compat_scan",
            "ok": True,
            "sql_compat_ready": compat.get("sql_compat_ready"),
            "high": summary.get("high"),
            "medium": summary.get("medium"),
            "total": summary.get("total"),
            "runtime_blockers": risk_summary.get("runtime_blocker"),
            "schema_migration": risk_summary.get("schema_migration"),
            "adapter_covered": risk_summary.get("adapter_covered"),
            "adapter_candidate": risk_summary.get("adapter_candidate"),
        })
    except Exception as exc:
        report["checks"].append({"name": "sql_compat_scan", "ok": False, "error": str(exc)})
        report["blockers"].append(f"SQL compat scan failed: {exc}")

    report["ok"] = all(bool(c.get("ok")) for c in report["checks"])
    report["finished_at"] = datetime.now().isoformat(timespec="seconds")
    return report


def main() -> int:
    report = runtime_simulation()
    print("POSTGRES_RUNTIME_SIM_" + ("OK" if report.get("ok") else "FAIL"))
    for check in report.get("checks") or []:
        print(f"  [{'OK' if check.get('ok') else 'ERR'}] {check.get('name')}")
    print(json.dumps(report, ensure_ascii=False, indent=2))
    return 0 if report.get("ok") else 1


if __name__ == "__main__":
    raise SystemExit(main())
